apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: true
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}

  - name: LibreNMS-DB
    uid: librenms_mysql
    type: mysql
    access: proxy
    url: db:3306
    user: ${MYSQL_USER}
    editable: true
    jsonData:
      database: ${MYSQL_DATABASE}
      maxOpenConns: 25
      maxIdleConns: 25
      connMaxLifetime: 14400
    secureJsonData:
      password: ${MYSQL_PASSWORD}
